export interface Entity {
  record: any;
  x: any;
  y: any;
  z: any;
  references: any;
  inlimbo: boolean;
  inherentactions: any;
  updatecomponents: any;
  cmpname: any;
  num: number;
  wallupdatecomponents: any;
  lower_name: any;
  cmp: any;
  loadedcmp: any;
  postinitfns: any;
  name: any;
  equippable: any;
  eslot: any;
  name_extention: any;
  replica: any;
  skin_build_name: any;
  prefab: any;
  nameoverride: any;
  deploy_extra_spacing: any;
  terraform_extra_spacing: any;
  ground_target_blocker_radius: any;
  inst: any;
  children: any;
  str: any;
  cmpkeys: any;
  fn: any;
  brain: any;
  brainfn: any;
  sg: any;
  event_listening: any;
  event_listeners: any;
  worldstatewatching: any;
  listeners: any;
  tocall: any;
  physicsradiusoverride: any;
  x1: any;
  y1: any;
  z1: any;
  p1: any;
  p2: any;
  offset: any;
  p1x: any;
  p1y: any;
  p1z: any;
  p2x: any;
  p2y: any;
  p2z: any;
  player: any;
  distsq: any;
  pendingtasks: any;
  per: any;
  taskinfo: any;
  timeleft: any;
  task: any;
  bufferedaction: any;
  ispreviewing: boolean;
  success: any;
  reason: any;
  persists: boolean;
  parent: any;
  inventory: any;
  item: any;
  platform: any;
  map: any;
  ptx: any;
  pty: any;
  ptz: any;
  tilecenter_x: any;
  tilecenter_y: any;
  tilecenter_z: any;
  tx: any;
  ty: any;
  actual_tile: any;
  xpercent: any;
  ypercent: any;
  x_min: any;
  x_max: any;
  y_min: any;
  y_max: any;
  x_off: number;
  y_off: number;
  dest: any;
  data: any;
  refs: any;
  inherentsceneaction: any;
  inherentscenealtaction: any;
  AddChild(child: any): any;
  AddComponent(name: any): any;
  AddInherentAction(act: any): any;
  AddTag(tag: any): any;
  CanDoAction(action: any): boolean;
  CanInteractWith(inst: any): boolean;
  CancelAllPendingTasks(): any;
  ClearBufferedAction(): any;
  ClearStateGraph(): any;
  DoPeriodicTask(time: any, fn: any, initialdelay: any): any;
  DoTaskInTime(time: any, fn: any): any;
  FaceAwayFromPoint(dest: any, force: any): any;
  FacePoint(x: any, y: any, z: any): any;
  ForceFacePoint(x: any, y: any, z: any): any;
  GetAdjective(): any;
  GetAdjectivedName(): any;
  GetAngleToPoint(x: any, y: any, z: any): any;
  GetBasicDisplayName(): any;
  GetBrainString(): any;
  GetBufferedAction(): any;
  GetComponentName(cmp: any): any;
  GetCurrentPlatform(): any;
  GetCurrentTileType(): any;
  GetDebugString(): any;
  GetDisplayName(): any;
  GetDistanceSqToClosestPlayer(isalive: any): any;
  GetDistanceSqToInst(inst: any): any;
  GetDistanceSqToPoint(x: any, y: any, z: any): any;
  GetIsWet(): any;
  GetNearestPlayer(isalive: any): any;
  GetPersistData(): any;
  GetPhysicsRadius(_default: any): any;
  GetPosition(): any;
  GetPositionAdjacentTo(target: any, distance: any): any;
  GetRotation(): any;
  GetSaveRecord(): any;
  GetSkinBuild(): any;
  GetSkinName(): any;
  GetTaskInfo(time: any): any;
  GetTimeAlive(): any;
  HasTag(tag: any): boolean;
  Hide(): any;
  IsAsleep(): boolean;
  IsInLimbo(): boolean;
  IsNear(otherinst: any, dist: any): boolean;
  IsNearPlayer(range: any, isalive: any): boolean;
  IsOnPassablePoint(
    include_water: any,
    floating_platforms_are_not_passable: any
  ): boolean;
  IsOnValidGround(): boolean;
  IsValid(): boolean;
  KillTasks(): any;
  ListenForEvent(event: any, fn: any, source: any): any;
  LoadPostPass(newents: any, savedata: any): any;
  LongUpdate(dt: any): any;
  OnBuilt(builder: any): any;
  OnUsedAsItem(action: any): any;
  PerformBufferedAction(): any;
  PerformPreviewBufferedAction(): any;
  PreviewBufferedAction(bufferedaction: any): any;
  PushBufferedAction(bufferedaction: any): any;
  PushEvent(event: any, data: any): any;
  PutBackOnGround(): any;
  Remove(): any;
  RemoveAllEventCallbacks(): any;
  RemoveChild(child: any): any;
  RemoveComponent(name: any): any;
  RemoveEventCallback(event: any, fn: any, source: any): any;
  RemoveFromScene(): any;
  RemoveInherentAction(act: any): any;
  RemoveTag(tag: any): any;
  RestartBrain(): any;
  ResumeTask(time: any, fn: any): any;
  ReturnToScene(): any;
  RunScript(name: any): any;
  SetBrain(brainfn: any): any;
  SetDeployExtraSpacing(spacing: any): any;
  SetGroundTargetBlockerRadius(radius: any): any;
  SetInherentSceneAction(action: any): any;
  SetInherentSceneAltAction(action: any): any;
  SetPersistData(data: any, newents: any): any;
  SetPhysicsRadiusOverride(radius: any): any;
  SetPrefabName(name: any): any;
  SetPrefabNameOverride(nameoverride: any): any;
  SetStateGraph(name: any): any;
  SetTerraformExtraSpacing(spacing: any): any;
  Show(): any;
  SpawnChild(name: any): any;
  StartThread(fn: any): any;
  StartUpdatingComponent(cmp: any): any;
  StartWallUpdatingComponent(cmp: any): any;
  StopAllWatchingWorldStates(): any;
  StopBrain(): any;
  StopUpdatingComponent(cmp: any): any;
  StopUpdatingComponent_Deferred(cmp: any): any;
  StopWallUpdatingComponent(cmp: any): any;
  StopWatchingWorldState(_var: any, fn: any): any;
  TimeRemainingInTask(taskinfo: any): any;
  WatchWorldState(_var: any, fn: any): any;
}
